name = 'waalge/coerce_data'
version = '0.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project 'waalge/coerce_data'"

[repository]
user = 'waalge'
project = 'coerce_data'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = 'main'
source = 'github'
