name = 'waalge/data_issue'
version = '0.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project 'waalge/data_issue'"

[repository]
user = 'waalge'
project = 'data_issue'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = 'main'
source = 'github'
